// <auto-generated />
namespace SDSolutionsApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editforeignkey2202023 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editforeignkey2202023));
        
        string IMigrationMetadata.Id
        {
            get { return "202302200637257_editforeignkey-2-20-2023"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
